[package]
name = "phaser_math"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
glam.workspace = true
serde.workspace = true

[dev-dependencies]
proptest.workspace = true
